from pathlib import Path

import pytest
from PyQt6.QtCore import Qt

from in_reach.app import env_file, system_verify
from in_reach.ide.explorer import ExplorerPanel


@pytest.fixture
def panel(qtbot) -> ExplorerPanel:
    widget = ExplorerPanel()
    qtbot.addWidget(widget)
    widget.show()  # isVisible() reflects real state only once the whole ancestor chain is shown
    return widget


def test_starts_with_no_project_placeholder_shown_and_boxes_hidden(panel: ExplorerPanel) -> None:
    assert panel._no_project_label.isVisible() is True
    assert panel.script_section.isVisible() is False
    assert panel.settings_section.isVisible() is False
    assert panel.stats_section.isVisible() is False


def test_open_project_shows_the_script_and_settings_boxes_rooted_at_it(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    folder.mkdir()

    panel.open_project(folder)

    assert panel._no_project_label.isVisible() is False
    assert panel.script_section.isVisible() is True
    assert panel.settings_section.isVisible() is True
    assert Path(panel._script_model.rootPath()) == folder / "script"
    assert Path(panel._settings_model.rootPath()) == folder / "settings"


def test_close_all_projects_restores_the_placeholder(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_all_projects()

    assert panel._no_project_label.isVisible() is True
    assert panel.script_section.isVisible() is False
    assert panel.settings_section.isVisible() is False


def test_opening_a_nonexistent_project_folder_is_a_no_op(panel: ExplorerPanel, tmp_path: Path) -> None:
    panel.open_project(tmp_path / "does-not-exist")

    assert panel._no_project_label.isVisible() is True
    assert panel.script_section.isVisible() is False
    assert panel.open_projects == []


# -- Script/Settings boxes (PROMPT.md: "boxes like Personal Game Variants for Script and Settings")


def test_script_and_settings_sections_are_hidden_with_no_project_open(panel: ExplorerPanel) -> None:
    assert panel.script_section.isVisible() is False
    assert panel.settings_section.isVisible() is False


def test_opening_a_project_points_the_script_and_settings_trees_at_its_own_subfolders(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    (folder / "script").mkdir(parents=True)
    (folder / "settings").mkdir(parents=True)

    panel.open_project(folder)

    assert panel.script_section.isVisible() is True
    assert panel.settings_section.isVisible() is True
    assert Path(panel._script_model.rootPath()) == folder / "script"
    assert Path(panel._settings_model.rootPath()) == folder / "settings"


def test_closing_the_last_project_hides_the_script_and_settings_sections_again(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_all_projects()

    assert panel.script_section.isVisible() is False
    assert panel.settings_section.isVisible() is False


def test_clicking_a_file_in_the_script_section_emits_file_activated(
    panel: ExplorerPanel, qtbot, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    (folder / "script").mkdir(parents=True)
    output_txt = folder / "script" / "output.txt"
    output_txt.write_text("-- script --", encoding="utf-8")
    panel.open_project(folder)
    model = panel._script_model
    qtbot.waitUntil(lambda: model.rowCount(panel.script_tree.rootIndex()) > 0, timeout=2000)

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel.script_tree.clicked.emit(model.index(str(output_txt)))

    assert activated == [output_txt]


# -- the Stats box (PROMPT.md: "please also add a stats view into the dashboard") ----------------


def test_stats_box_shows_the_placeholder_with_no_project_open(panel: ExplorerPanel) -> None:
    assert panel.stats_section.isVisible() is False
    assert "No build stats" in panel.stats_label.text()


def test_no_stats_file_shows_the_placeholder_and_hides_the_progress_bar(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    (folder / "build").mkdir(parents=True)  # no stats.autogenerated.json written

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is False
    assert "No build stats" in panel.stats_label.text()


def test_a_real_stats_file_populates_the_progress_bar_and_counts(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    import json

    folder = tmp_path / "project"
    build_dir = folder / "build"
    build_dir.mkdir(parents=True)
    (build_dir / "stats.autogenerated.json").write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 100, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 1, "option_toggles": 1, "rating_params": 1,
                        "map_perms": 1, "script_content": 1, "script_stats": 1,
                        "script_widgets": 1, "forge_labels": 1, "title_update_1": 1,
                    },
                    "bytes_used": 100,
                    "bytes_max": 200,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": 3, "conditions": 4, "actions": 5, "forge_labels": 1,
                    "strings": 2, "script_options": 0, "script_stats": 0,
                    "script_traits": 0, "script_widgets": 0,
                },
            }
        ),
        encoding="utf-8",
    )

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is True
    assert panel.stats_progress.value() == 50
    assert "100" in panel.stats_label.text() and "200" in panel.stats_label.text()
    assert "Triggers: 3" in panel.stats_label.text()


def _write_strings_json(path: Path, entries: int) -> None:
    import json

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "meta": {"name": [], "description": [], "category": []},
                "teams": [],
                "script_strings": [{"index": i, "text": f"str{i}"} for i in range(entries)],
            }
        ),
        encoding="utf-8",
    )


def test_stats_box_shows_the_strings_count_even_with_no_build_stats(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    # PROMPT.md: "please also make stats include[] strings.json" -- settings/strings.json is
    # written for every project, multiplayer or not, unlike build/stats.autogenerated.json (only a
    # compiled multiplayer gametype gets one) -- so a project with no build stats yet should still
    # show a strings count.
    folder = tmp_path / "project"
    _write_strings_json(folder / "settings" / "strings.json", 5)

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is False
    assert "Strings: 5" in panel.stats_label.text()
    assert "No build stats" not in panel.stats_label.text()


def test_stats_box_shows_both_build_stats_and_strings_count_together(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    import json

    folder = tmp_path / "project"
    build_dir = folder / "build"
    build_dir.mkdir(parents=True)
    (build_dir / "stats.autogenerated.json").write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 100, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 1, "option_toggles": 1, "rating_params": 1,
                        "map_perms": 1, "script_content": 1, "script_stats": 1,
                        "script_widgets": 1, "forge_labels": 1, "title_update_1": 1,
                    },
                    "bytes_used": 100,
                    "bytes_max": 200,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": 3, "conditions": 4, "actions": 5, "forge_labels": 1,
                    "strings": 2, "script_options": 0, "script_stats": 0,
                    "script_traits": 0, "script_widgets": 0,
                },
            }
        ),
        encoding="utf-8",
    )
    _write_strings_json(folder / "settings" / "strings.json", 7)

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is True
    assert "Triggers: 3" in panel.stats_label.text()
    assert "Strings: 7" in panel.stats_label.text()


def test_refresh_stats_re_reads_the_stats_file_for_the_current_project(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    build_dir = folder / "build"
    build_dir.mkdir(parents=True)
    panel.open_project(folder)
    assert panel.stats_progress.isVisible() is False

    import json

    (build_dir / "stats.autogenerated.json").write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 8, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 0, "option_toggles": 0, "rating_params": 0,
                        "map_perms": 0, "script_content": 0, "script_stats": 0,
                        "script_widgets": 0, "forge_labels": 0, "title_update_1": 0,
                    },
                    "bytes_used": 1,
                    "bytes_max": 2,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": 0, "conditions": 0, "actions": 0, "forge_labels": 0,
                    "strings": 0, "script_options": 0, "script_stats": 0,
                    "script_traits": 0, "script_widgets": 0,
                },
            }
        ),
        encoding="utf-8",
    )

    panel.refresh_stats()

    assert panel.stats_progress.isVisible() is True


# -- the two personal-folder sections -----------------------------------------------------------


@pytest.fixture
def env_project_dir(tmp_path: Path) -> Path:
    project_dir = tmp_path / ".in-reach"
    project_dir.mkdir()
    (project_dir / ".env").write_text("", encoding="utf-8")
    return project_dir


# Sections start collapsed (see the "collapsible sections" tests below), so a nested tree/
# placeholder's own isVisible() reflects the whole ancestor chain including that collapse -- these
# tests care about the resolved-vs-placeholder state on its own, so they check visibility relative
# to the section's own body instead (see QWidget.isVisibleTo's own docs).


def test_personal_sections_start_with_the_not_resolved_placeholder(
    panel: ExplorerPanel, env_project_dir: Path
) -> None:
    panel.set_env_project_dir(env_project_dir)

    body1 = panel.personal_variants_section.body
    body2 = panel.personal_maps_section.body
    assert panel.personal_variants_placeholder.isVisibleTo(body1) is True
    assert panel.personal_variants_tree.isVisibleTo(body1) is False
    assert panel.personal_maps_placeholder.isVisibleTo(body2) is True
    assert panel.personal_maps_tree.isVisibleTo(body2) is False


def test_personal_sections_resolve_once_the_env_keys_are_set(
    panel: ExplorerPanel, env_project_dir: Path, tmp_path: Path
) -> None:
    variants = tmp_path / "variants"
    variants.mkdir()
    maps = tmp_path / "maps"
    maps.mkdir()
    env_file.update_env_value(env_project_dir / ".env", system_verify.PERSONAL_VARIANTS_KEY, str(variants))
    env_file.update_env_value(env_project_dir / ".env", system_verify.PERSONAL_MAPS_KEY, str(maps))

    panel.set_env_project_dir(env_project_dir)

    body1 = panel.personal_variants_section.body
    body2 = panel.personal_maps_section.body
    assert panel.personal_variants_placeholder.isVisibleTo(body1) is False
    assert panel.personal_variants_tree.isVisibleTo(body1) is True
    assert Path(panel._personal_variants_model.rootPath()) == variants
    assert panel.personal_maps_placeholder.isVisibleTo(body2) is False
    assert panel.personal_maps_tree.isVisibleTo(body2) is True
    assert Path(panel._personal_maps_model.rootPath()) == maps


def test_refresh_personal_folders_picks_up_a_later_verify(
    panel: ExplorerPanel, env_project_dir: Path, tmp_path: Path
) -> None:
    panel.set_env_project_dir(env_project_dir)
    body = panel.personal_variants_section.body
    assert panel.personal_variants_tree.isVisibleTo(body) is False

    variants = tmp_path / "variants"
    variants.mkdir()
    env_file.update_env_value(env_project_dir / ".env", system_verify.PERSONAL_VARIANTS_KEY, str(variants))
    panel.refresh_personal_folders()

    assert panel.personal_variants_tree.isVisibleTo(body) is True


def test_set_env_project_dir_none_clears_both_sections(
    panel: ExplorerPanel, env_project_dir: Path, tmp_path: Path
) -> None:
    variants = tmp_path / "variants"
    variants.mkdir()
    env_file.update_env_value(env_project_dir / ".env", system_verify.PERSONAL_VARIANTS_KEY, str(variants))
    panel.set_env_project_dir(env_project_dir)
    body = panel.personal_variants_section.body
    assert panel.personal_variants_tree.isVisibleTo(body) is True

    panel.set_env_project_dir(None)

    assert panel.personal_variants_placeholder.isVisibleTo(body) is True
    assert panel.personal_variants_tree.isVisibleTo(body) is False


# -- collapsible sections -------------------------------------------------------------------------


def test_personal_sections_start_collapsed(panel: ExplorerPanel) -> None:
    assert panel.personal_variants_section.expanded is False
    assert panel.personal_maps_section.expanded is False
    assert panel.personal_variants_section.body.isVisible() is False


def test_clicking_a_section_header_expands_it(panel: ExplorerPanel, qtbot) -> None:
    qtbot.mouseClick(panel.personal_variants_section._toggle, Qt.MouseButton.LeftButton)

    assert panel.personal_variants_section.expanded is True
    assert panel.personal_variants_section.body.isVisible() is True


# -- clicking a file opens it ----------------------------------------------------------------------


def test_clicking_a_file_in_the_settings_section_via_the_real_signal_emits_file_activated(
    panel: ExplorerPanel, qtbot, tmp_path: Path
) -> None:
    # Unlike test_clicking_a_file_in_the_script_section_emits_file_activated above (which drives
    # the private handler directly), this fires the tree's own `clicked` signal -- confirming the
    # Settings box really is wired up, the mirror image of the "personal folders are NOT wired up"
    # tests below.
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)
    file_path = folder / "settings" / "settings.json"
    file_path.write_text("{}", encoding="utf-8")
    model = panel._settings_model
    # rootIndex() is re-fetched fresh inside the lambda (not captured once beforehand) --
    # QFileSystemModel can rebuild its internal node tree the first time it visits a brand new
    # subtree, silently invalidating a QModelIndex captured before that settles; querying a stale
    # one afterward is undefined behavior (observed: wrong rows, or an outright native crash).
    qtbot.waitUntil(lambda: model.rowCount(panel.settings_tree.rootIndex()) > 0, timeout=2000)

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel.settings_tree.clicked.emit(model.index(str(file_path)))

    assert activated == [file_path]


def test_clicking_a_folder_does_not_emit_file_activated(panel: ExplorerPanel, qtbot, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    (folder / "script" / "subfolder").mkdir(parents=True)
    panel.open_project(folder)
    model = panel._script_model
    qtbot.waitUntil(lambda: model.rowCount(panel.script_tree.rootIndex()) > 0, timeout=2000)
    dir_index = model.index(str(folder / "script" / "subfolder"))

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel._on_tree_clicked(model, dir_index)

    assert activated == []


def test_an_invalid_index_does_not_emit_file_activated(panel: ExplorerPanel) -> None:
    from PyQt6.QtCore import QModelIndex

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)

    panel._on_tree_clicked(panel._script_model, QModelIndex())

    assert activated == []


def test_clicking_a_file_in_a_personal_folder_section_does_not_open_it(
    panel: ExplorerPanel, qtbot, tmp_path: Path
) -> None:
    # PROMPT.md: "disable clicking on personal game variants of personal map variants window for
    # now" -- those are raw .bin/.mvar files, and opening one as text just raised an error. Clicks
    # in either personal-folder tree are simply never wired to file_activated at all (see
    # ExplorerPanel.__init__) -- this drives the real `clicked` signal, not the private handler
    # directly, so it actually exercises that wiring (or lack of it) rather than just the handler.
    project_dir = tmp_path / ".in-reach"
    project_dir.mkdir()
    (project_dir / ".env").write_text("", encoding="utf-8")
    variants = tmp_path / "variants"
    variants.mkdir()
    file_path = variants / "Slayer.bin"
    file_path.write_bytes(b"")
    env_file.update_env_value(project_dir / ".env", system_verify.PERSONAL_VARIANTS_KEY, str(variants))
    panel.set_env_project_dir(project_dir)
    model = panel._personal_variants_model
    qtbot.waitUntil(lambda: model.rowCount(panel.personal_variants_tree.rootIndex()) > 0, timeout=2000)
    file_index = model.index(str(file_path))

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel.personal_variants_tree.clicked.emit(file_index)

    assert activated == []


def test_clicking_a_file_in_the_personal_maps_section_also_does_not_open_it(
    panel: ExplorerPanel, qtbot, tmp_path: Path
) -> None:
    project_dir = tmp_path / ".in-reach"
    project_dir.mkdir()
    (project_dir / ".env").write_text("", encoding="utf-8")
    maps = tmp_path / "maps"
    maps.mkdir()
    file_path = maps / "Forge.mvar"
    file_path.write_bytes(b"")
    env_file.update_env_value(project_dir / ".env", system_verify.PERSONAL_MAPS_KEY, str(maps))
    panel.set_env_project_dir(project_dir)
    model = panel._personal_maps_model
    qtbot.waitUntil(lambda: model.rowCount(panel.personal_maps_tree.rootIndex()) > 0, timeout=2000)
    file_index = model.index(str(file_path))

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel.personal_maps_tree.clicked.emit(file_index)

    assert activated == []


# -- text scale -------------------------------------------------------------------------------


def test_panel_font_is_10_percent_larger_than_the_app_font(panel: ExplorerPanel) -> None:
    from PyQt6.QtWidgets import QApplication

    app_size = QApplication.instance().font().pointSizeF()

    assert panel.font().pointSizeF() == pytest.approx(app_size * ExplorerPanel.TEXT_SCALE)


def test_refresh_font_scale_tracks_a_later_app_font_change(panel: ExplorerPanel) -> None:
    from PyQt6.QtGui import QFont
    from PyQt6.QtWidgets import QApplication

    app = QApplication.instance()
    original = QFont(app.font())
    try:
        bigger = QFont(original)
        bigger.setPointSizeF(original.pointSizeF() * 2)
        app.setFont(bigger)

        panel.refresh_font_scale()

        assert panel.font().pointSizeF() == pytest.approx(bigger.pointSizeF() * ExplorerPanel.TEXT_SCALE)
    finally:
        app.setFont(original)


def test_personal_section_headers_are_10_percent_smaller_than_the_panel_font(panel: ExplorerPanel) -> None:
    panel_size = panel.font().pointSizeF()

    for section in (panel.personal_variants_section, panel.personal_maps_section):
        assert section._toggle.font().pointSizeF() == pytest.approx(
            panel_size * ExplorerPanel.HEADER_TEXT_SCALE
        )


# -- multi-project tabs ------------------------------------------------------------------------


def test_project_tabs_are_hidden_with_no_project(panel: ExplorerPanel) -> None:
    assert panel.project_tabs.isVisible() is False
    assert panel.project_tabs.count() == 0


def test_open_project_adds_a_tab_labeled_with_the_projects_own_title(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "abcd1234"
    (folder / "settings").mkdir(parents=True)
    (folder / "settings" / "settings.json").write_text(
        '{"meta": {"title": "Slayer Plus"}}', encoding="utf-8"
    )

    panel.open_project(folder)

    assert panel.project_tabs.isVisible() is True
    assert panel.project_tabs.count() == 1
    assert panel.project_tabs.tabText(0) == "Slayer Plus"
    assert panel.open_projects == [folder]
    assert panel.current_folder == folder


def test_open_project_tab_falls_back_to_the_folder_name_without_a_settings_json(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()

    panel.open_project(folder)

    assert panel.project_tabs.tabText(0) == "abcd1234"


def test_opening_an_already_open_project_switches_instead_of_duplicating(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    panel.open_project(first)
    panel.open_project(second)

    panel.open_project(first)

    assert panel.project_tabs.count() == 2
    assert panel.open_projects == [first, second]
    assert panel.current_folder == first


def test_opening_a_second_project_adds_a_tab_without_closing_the_first(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()

    panel.open_project(first)
    panel.open_project(second)

    assert panel.project_tabs.count() == 2
    assert panel.open_projects == [first, second]
    assert panel.current_folder == second
    assert Path(panel._settings_model.rootPath()) == second / "settings"


def test_close_project_switches_to_a_remaining_tab(panel: ExplorerPanel, tmp_path: Path) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    panel.open_project(first)
    panel.open_project(second)

    panel.close_project(second)

    assert panel.open_projects == [first]
    assert panel.current_folder == first
    assert panel.project_tabs.isVisible() is True


def test_close_project_of_the_last_tab_restores_the_placeholder(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_project(folder)

    assert panel.open_projects == []
    assert panel.current_folder is None
    assert panel._no_project_label.isVisible() is True
    assert panel.script_section.isVisible() is False
    assert panel.project_tabs.isVisible() is False


def test_close_active_project_closes_whichever_tab_is_current(panel: ExplorerPanel, tmp_path: Path) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    panel.open_project(first)
    panel.open_project(second)

    panel.close_active_project()

    assert panel.open_projects == [first]
    assert panel.current_folder == first


def test_close_active_project_with_no_project_open_is_a_no_op(panel: ExplorerPanel) -> None:
    panel.close_active_project()  # should not raise

    assert panel.open_projects == []


def test_closing_a_background_tab_does_not_change_the_active_project(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    panel.open_project(first)
    panel.open_project(second)

    panel.close_project(first)

    assert panel.open_projects == [second]
    assert panel.current_folder == second


def test_tab_close_button_closes_that_projects_tab(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()
    panel.open_project(folder)

    # Drives the tab bar's own close-request signal, not close_project() directly -- confirms the
    # close (X) button is actually wired up.
    panel.project_tabs.tabCloseRequested.emit(0)

    assert panel.open_projects == []


def test_active_project_changed_fires_on_open_switch_and_close(panel: ExplorerPanel, tmp_path: Path) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    seen: list[Path | None] = []
    panel.active_project_changed.connect(seen.append)

    panel.open_project(first)
    panel.open_project(second)
    panel.open_project(first)  # switch back -- "first" is active again
    panel.close_project(first)  # closing the *active* tab -- "second" becomes active
    panel.close_project(second)  # last one -- back to no project

    assert seen == [first, second, first, second, None]


def test_open_projects_changed_fires_on_open_and_close_but_not_on_switch(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    seen: list[list[Path]] = []
    panel.open_projects_changed.connect(seen.append)

    panel.open_project(first)
    panel.open_project(second)
    panel.open_project(first)  # already open -- just switches, no set change
    panel.close_project(second)

    assert seen == [[first], [first, second], [first]]


# -- folder subheading / personal-section placement ----------------------------------------------


def test_folder_subheading_is_hidden_with_no_project(panel: ExplorerPanel) -> None:
    assert panel.folder_subheading.isVisible() is False
    assert panel.folder_subheading.text() == ""


def test_folder_subheading_shows_the_folders_own_name(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()

    panel.open_project(folder)

    # The folder's own id, not the (human-typed) title shown in the tab itself.
    assert panel.folder_subheading.text() == "abcd1234"
    assert panel.folder_subheading.isVisible() is True


def test_folder_subheading_hides_again_once_the_project_closes(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_project(folder)

    assert panel.folder_subheading.isVisible() is False
    assert panel.folder_subheading.text() == ""


def test_no_project_spacer_is_visible_only_with_no_project_open(panel: ExplorerPanel, tmp_path: Path) -> None:
    # PROMPT.md: "when no project is open, the Personal Game Variants and Personal Map Variants
    # should appear at the bottom of the file explorer panel".
    assert panel._no_project_spacer.isVisible() is True

    folder = tmp_path / "abcd1234"
    folder.mkdir()
    panel.open_project(folder)
    assert panel._no_project_spacer.isVisible() is False

    panel.close_project(folder)
    assert panel._no_project_spacer.isVisible() is True
