from pathlib import Path

import pytest
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QFrame, QLabel

from in_reach_ide.explorer import ExplorerPanel


@pytest.fixture
def panel(qtbot) -> ExplorerPanel:
    widget = ExplorerPanel()
    qtbot.addWidget(widget)
    widget.show()  # isVisible() reflects real state only once the whole ancestor chain is shown
    return widget


# -- no bordered "bubble" chrome ---------------------------------------------------------------


def test_settings_tree_has_no_default_frame_border(panel: ExplorerPanel) -> None:
    # PROMPT.md: "please remove the bubble outline around ... setings, and output.mgl" -- QTreeView
    # (like every QAbstractScrollArea) defaults to a sunken StyledPanel frame around itself.
    assert panel.settings_tree.frameShape() == QFrame.Shape.NoFrame


def test_stats_progress_bar_has_no_border(panel: ExplorerPanel) -> None:
    # PROMPT.md: "please remove the bubble outline around triggers conditions actions, forge
    # lables and strings" -- Fusion's default QProgressBar is a rounded, bordered pill sitting
    # directly above those lines.
    assert "border: none" in panel.stats_progress.styleSheet()


def test_progress_bars_are_smaller_than_fusions_own_default_height(panel: ExplorerPanel) -> None:
    # PROMPT.md: "please in the dashboard make the progress bars a little smaller (they're a bit
    # imposing at the moment)".
    from in_reach_ide.explorer import _PROGRESS_BAR_HEIGHT

    assert panel.stats_progress.height() == _PROGRESS_BAR_HEIGHT
    assert panel.trigger_stat.progress.height() == _PROGRESS_BAR_HEIGHT
    assert _PROGRESS_BAR_HEIGHT < 20  # meaningfully smaller than Fusion's own ~23px default


def test_starts_with_no_project_placeholder_shown_and_boxes_hidden(panel: ExplorerPanel) -> None:
    assert panel._no_project_label.isVisible() is True
    assert panel.settings_section.isVisible() is False
    assert panel.stats_section.isVisible() is False


def test_open_project_shows_the_settings_box_rooted_at_it(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    folder.mkdir()

    panel.open_project(folder)

    assert panel._no_project_label.isVisible() is False
    assert panel.settings_section.isVisible() is True
    assert Path(panel._settings_model.rootPath()) == folder / "settings"


def test_close_active_project_restores_the_placeholder(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_active_project()

    assert panel._no_project_label.isVisible() is True
    assert panel.settings_section.isVisible() is False


def test_opening_a_nonexistent_project_folder_is_a_no_op(panel: ExplorerPanel, tmp_path: Path) -> None:
    panel.open_project(tmp_path / "does-not-exist")

    assert panel._no_project_label.isVisible() is True
    assert panel.settings_section.isVisible() is False
    assert panel.current_folder is None


# -- Settings box (PROMPT.md: "boxes like Personal Game Variants for Script and Settings")


def test_settings_section_is_hidden_with_no_project_open(panel: ExplorerPanel) -> None:
    assert panel.settings_section.isVisible() is False


def test_opening_a_project_points_the_settings_tree_at_its_own_subfolder(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    (folder / "settings").mkdir(parents=True)

    panel.open_project(folder)

    assert panel.settings_section.isVisible() is True
    assert Path(panel._settings_model.rootPath()) == folder / "settings"


def test_closing_the_last_project_hides_the_settings_section_again(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_active_project()

    assert panel.settings_section.isVisible() is False


# -- the Stats box (PROMPT.md: "please also add a stats view into the dashboard") ----------------


def test_stats_box_shows_the_placeholder_with_no_project_open(panel: ExplorerPanel) -> None:
    assert panel.stats_section.isVisible() is False
    assert "No build stats" in panel.stats_label.text()


def test_no_stats_file_shows_the_placeholder_and_hides_the_progress_bar(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    (folder / "build").mkdir(parents=True)  # no stats.autogenerated.json written

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is False
    assert panel.stats_grid_widget.isVisible() is False
    assert "No build stats" in panel.stats_label.text()


def test_a_real_stats_file_populates_the_progress_bar_and_counts(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    import json

    folder = tmp_path / "project"
    build_dir = folder / "build"
    build_dir.mkdir(parents=True)
    (build_dir / "stats.autogenerated.json").write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 100, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 1, "option_toggles": 1, "rating_params": 1,
                        "map_perms": 1, "script_content": 1, "script_stats": 1,
                        "script_widgets": 1, "forge_labels": 1, "title_update_1": 1,
                    },
                    "bytes_used": 100,
                    "bytes_max": 200,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": 3, "conditions": 4, "actions": 5, "forge_labels": 1,
                    "strings": 2, "script_options": 0, "script_stats": 0,
                    "script_traits": 0, "script_widgets": 0,
                },
            }
        ),
        encoding="utf-8",
    )

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is True
    assert panel.stats_progress.value() == 50
    # PROMPT.md: "please combine the percentage used bar to be: 10,874 / 20520 B used (53%) (and
    # with the progress bar background)" -- shown as the progress bar's own text, not a label line.
    assert "100" in panel.stats_progress.text() and "200" in panel.stats_progress.text()
    # PROMPT.md: "please make each the 'sub' stats have a percentage bar and a border" -- each of
    # Triggers/Conditions/Actions/Forge Labels gets its own bordered _StatBox, visible once real
    # counts exist.
    assert panel.stats_grid_widget.isVisible() is True
    assert panel.trigger_stat.isVisible() is True
    assert "Triggers: 3" in panel.trigger_stat.progress.text()


def _write_strings_json(path: Path, entries: int) -> None:
    import json

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "meta": {"name": [], "description": [], "category": []},
                "teams": [],
                "script_strings": [{"index": i, "text": f"str{i}"} for i in range(entries)],
            }
        ),
        encoding="utf-8",
    )


def test_stats_box_shows_the_strings_count_even_with_no_build_stats(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    # PROMPT.md: "please also make stats include[] strings.json" -- settings/strings.json is
    # written for every project, multiplayer or not, unlike build/stats.autogenerated.json (only a
    # compiled multiplayer gametype gets one) -- so a project with no build stats yet should still
    # show a strings count.
    folder = tmp_path / "project"
    _write_strings_json(folder / "settings" / "strings.json", 5)

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is False
    assert panel.stats_grid_widget.isVisible() is True
    assert panel.string_stat.isVisible() is True
    assert "Strings: 5" in panel.string_stat.progress.text()
    assert panel.stats_label.isVisible() is False


def _write_build_stats(
    path: Path,
    *,
    triggers: int,
    conditions: int,
    actions: int,
    forge_labels: int,
    script_options: int = 0,
    script_stats: int = 0,
    script_traits: int = 0,
    script_widgets: int = 0,
) -> None:
    import json

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 100, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 1, "option_toggles": 1, "rating_params": 1,
                        "map_perms": 1, "script_content": 1, "script_stats": 1,
                        "script_widgets": 1, "forge_labels": 1, "title_update_1": 1,
                    },
                    "bytes_used": 100,
                    "bytes_max": 200,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": triggers, "conditions": conditions, "actions": actions,
                    "forge_labels": forge_labels, "strings": 0, "script_options": script_options,
                    "script_stats": script_stats, "script_traits": script_traits,
                    "script_widgets": script_widgets,
                },
            }
        ),
        encoding="utf-8",
    )


def test_stats_box_shows_the_known_max_amounts_alongside_each_count(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    # PROMPT.md: "in the dashboard please also make it so that it also shows the max amount of
    # tiggers, conditions, actions, forge labels and strings (if known)" -- these five caps are
    # confirmed engine limits (see explorer.py's own _MAX_TRIGGERS et al.), not guesses.
    folder = tmp_path / "project"
    _write_build_stats(
        folder / "build" / "stats.autogenerated.json",
        triggers=3, conditions=4, actions=5, forge_labels=1,
    )
    _write_strings_json(folder / "settings" / "strings.json", 7)

    panel.open_project(folder)

    assert "Triggers: 3/320" in panel.trigger_stat.progress.text()
    assert "Conditions: 4/512" in panel.condition_stat.progress.text()
    # A real compile once confirmed this directly: "The compiled script contains 1052 actions, but
    # only a maximum of 1024 are allowed" -- 1024 is a plain confirmed cap, same as the other four.
    assert "Actions: 5/1024" in panel.action_stat.progress.text()
    assert "Forge Labels: 1/16" in panel.forge_label_stat.progress.text()
    assert "Strings: 7/112" in panel.string_stat.progress.text()


def test_stats_box_shows_the_remaining_script_counts_and_their_known_max_amounts(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    # PROMPT.md: "also in dashboard please add progress bars for the remaining script counts
    # (options, traits, stats, widgets)" -- confirmed engine caps (Megalo::Limits::max_script_
    # options/max_script_traits/max_script_stats/max_script_widgets, see explorer.py's own
    # _MAX_SCRIPT_OPTIONS et al.), not guesses.
    folder = tmp_path / "project"
    _write_build_stats(
        folder / "build" / "stats.autogenerated.json",
        triggers=0, conditions=0, actions=0, forge_labels=0,
        script_options=2, script_stats=1, script_traits=3, script_widgets=1,
    )

    panel.open_project(folder)

    assert panel.script_option_stat.isVisible() is True
    assert panel.script_trait_stat.isVisible() is True
    assert panel.script_stat_stat.isVisible() is True
    assert panel.script_widget_stat.isVisible() is True
    assert "Options: 2/16" in panel.script_option_stat.progress.text()
    assert "Traits: 3/16" in panel.script_trait_stat.progress.text()
    assert "Stats: 1/4" in panel.script_stat_stat.progress.text()
    assert "Widgets: 1/4" in panel.script_widget_stat.progress.text()


def test_stats_box_hides_script_counts_with_no_build_stats(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    _write_strings_json(folder / "settings" / "strings.json", 5)

    panel.open_project(folder)

    assert panel.script_option_stat.isVisible() is False
    assert panel.script_trait_stat.isVisible() is False
    assert panel.script_stat_stat.isVisible() is False
    assert panel.script_widget_stat.isVisible() is False


def test_stats_box_shows_the_max_string_count_even_with_no_build_stats(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    _write_strings_json(folder / "settings" / "strings.json", 5)

    panel.open_project(folder)

    assert "Strings: 5/112" in panel.string_stat.progress.text()


def test_stats_box_shows_both_build_stats_and_strings_count_together(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    import json

    folder = tmp_path / "project"
    build_dir = folder / "build"
    build_dir.mkdir(parents=True)
    (build_dir / "stats.autogenerated.json").write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 100, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 1, "option_toggles": 1, "rating_params": 1,
                        "map_perms": 1, "script_content": 1, "script_stats": 1,
                        "script_widgets": 1, "forge_labels": 1, "title_update_1": 1,
                    },
                    "bytes_used": 100,
                    "bytes_max": 200,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": 3, "conditions": 4, "actions": 5, "forge_labels": 1,
                    "strings": 2, "script_options": 0, "script_stats": 0,
                    "script_traits": 0, "script_widgets": 0,
                },
            }
        ),
        encoding="utf-8",
    )
    _write_strings_json(folder / "settings" / "strings.json", 7)

    panel.open_project(folder)

    assert panel.stats_progress.isVisible() is True
    assert "Triggers: 3" in panel.trigger_stat.progress.text()
    assert "Forge Labels: 1" in panel.forge_label_stat.progress.text()
    assert "Strings: 7" in panel.string_stat.progress.text()


def test_refresh_stats_re_reads_the_stats_file_for_the_current_project(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    build_dir = folder / "build"
    build_dir.mkdir(parents=True)
    panel.open_project(folder)
    assert panel.stats_progress.isVisible() is False

    import json

    (build_dir / "stats.autogenerated.json").write_text(
        json.dumps(
            {
                "space": {
                    "bits": {
                        "maximum": 8, "header": 1, "header_strings": 1, "cg_options": 1,
                        "team_config": 1, "script_traits": 1, "script_options": 1,
                        "script_strings": 0, "option_toggles": 0, "rating_params": 0,
                        "map_perms": 0, "script_content": 0, "script_stats": 0,
                        "script_widgets": 0, "forge_labels": 0, "title_update_1": 0,
                    },
                    "bytes_used": 1,
                    "bytes_max": 2,
                    "percent": 50.0,
                },
                "counts": {
                    "triggers": 0, "conditions": 0, "actions": 0, "forge_labels": 0,
                    "strings": 0, "script_options": 0, "script_stats": 0,
                    "script_traits": 0, "script_widgets": 0,
                },
            }
        ),
        encoding="utf-8",
    )

    panel.refresh_stats()

    assert panel.stats_progress.isVisible() is True


# -- collapsible sections -------------------------------------------------------------------------


def test_dashboard_sections_start_expanded(panel: ExplorerPanel) -> None:
    # PROMPT.md: "we then want boxes like Personal Game Variants for Script and Settings" (open by
    # default, unlike that now-removed section) -- Stats/Quick Launch/Settings are all central to
    # the active project, not secondary, so they start expanded rather than collapsed.
    for section in (panel.stats_section, panel.quick_launch_section, panel.settings_section):
        assert section.expanded is True


def test_clicking_a_section_header_collapses_and_expands_it(
    panel: ExplorerPanel, qtbot, tmp_path: Path
) -> None:
    # A project must be open, or settings_section itself (not just its body) is hidden -- so
    # body.isVisible() (which reflects the whole ancestor chain, not just the toggle's own state)
    # would read False regardless of what's toggled here.
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)

    qtbot.mouseClick(panel.settings_section._toggle, Qt.MouseButton.LeftButton)

    assert panel.settings_section.expanded is False
    assert panel.settings_section.body.isVisible() is False

    qtbot.mouseClick(panel.settings_section._toggle, Qt.MouseButton.LeftButton)

    assert panel.settings_section.expanded is True
    assert panel.settings_section.body.isVisible() is True


# -- clicking a file opens it ----------------------------------------------------------------------


def test_clicking_a_file_in_the_settings_section_via_the_real_signal_emits_file_activated(
    panel: ExplorerPanel, qtbot, tmp_path: Path
) -> None:
    # Fires the tree's own `clicked` signal (rather than driving the private handler directly) --
    # confirming the Settings box really is wired up.
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)
    file_path = folder / "settings" / "settings.json"
    file_path.write_text("{}", encoding="utf-8")
    model = panel._settings_model
    # rootIndex() is re-fetched fresh inside the lambda (not captured once beforehand) --
    # QFileSystemModel can rebuild its internal node tree the first time it visits a brand new
    # subtree, silently invalidating a QModelIndex captured before that settles; querying a stale
    # one afterward is undefined behavior (observed: wrong rows, or an outright native crash).
    qtbot.waitUntil(lambda: model.rowCount(panel.settings_tree.rootIndex()) > 0, timeout=2000)

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel.settings_tree.clicked.emit(model.index(str(file_path)))

    assert activated == [file_path]


def test_clicking_a_folder_does_not_emit_file_activated(panel: ExplorerPanel, qtbot, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    (folder / "settings" / "subfolder").mkdir(parents=True)
    panel.open_project(folder)
    model = panel._settings_model
    qtbot.waitUntil(lambda: model.rowCount(panel.settings_tree.rootIndex()) > 0, timeout=2000)
    dir_index = model.index(str(folder / "settings" / "subfolder"))

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)
    panel._on_tree_clicked(model, dir_index)

    assert activated == []


def test_an_invalid_index_does_not_emit_file_activated(panel: ExplorerPanel) -> None:
    from PyQt6.QtCore import QModelIndex

    activated: list[Path] = []
    panel.file_activated.connect(activated.append)

    panel._on_tree_clicked(panel._settings_model, QModelIndex())

    assert activated == []


# -- text scale -------------------------------------------------------------------------------


def test_panel_font_is_10_percent_larger_than_the_app_font(panel: ExplorerPanel) -> None:
    from PyQt6.QtWidgets import QApplication

    app_size = QApplication.instance().font().pointSizeF()

    assert panel.font().pointSizeF() == pytest.approx(app_size * ExplorerPanel.TEXT_SCALE)


def test_refresh_font_scale_tracks_a_later_app_font_change(panel: ExplorerPanel) -> None:
    from PyQt6.QtGui import QFont
    from PyQt6.QtWidgets import QApplication

    app = QApplication.instance()
    original = QFont(app.font())
    try:
        bigger = QFont(original)
        bigger.setPointSizeF(original.pointSizeF() * 2)
        app.setFont(bigger)

        panel.refresh_font_scale()

        assert panel.font().pointSizeF() == pytest.approx(bigger.pointSizeF() * ExplorerPanel.TEXT_SCALE)
    finally:
        app.setFont(original)


def test_section_headers_are_10_percent_smaller_than_the_panel_font(panel: ExplorerPanel) -> None:
    panel_size = panel.font().pointSizeF()

    for section in (panel.stats_section, panel.quick_launch_section, panel.settings_section):
        assert section._toggle.font().pointSizeF() == pytest.approx(
            panel_size * ExplorerPanel.HEADER_TEXT_SCALE
        )


def test_settings_tree_font_is_10_percent_larger_than_the_panel_font(panel: ExplorerPanel) -> None:
    # PROMPT.md: "in the dashboard panel please make the font for the settings jsons 10% bigger,
    # they look too small in the sidebar".
    panel_size = panel.font().pointSizeF()

    assert panel.settings_tree.font().pointSizeF() == pytest.approx(
        panel_size * ExplorerPanel.SETTINGS_TREE_TEXT_SCALE
    )


def test_settings_tree_font_tracks_a_later_app_font_change(panel: ExplorerPanel) -> None:
    from PyQt6.QtGui import QFont
    from PyQt6.QtWidgets import QApplication

    app = QApplication.instance()
    original = QFont(app.font())
    try:
        bigger = QFont(original)
        bigger.setPointSizeF(original.pointSizeF() * 2)
        app.setFont(bigger)

        panel.refresh_font_scale()

        expected = bigger.pointSizeF() * ExplorerPanel.TEXT_SCALE * ExplorerPanel.SETTINGS_TREE_TEXT_SCALE
        assert panel.settings_tree.font().pointSizeF() == pytest.approx(expected)
    finally:
        app.setFont(original)


# -- one project per window (PROMPT.md: "we now want it to be 1 per window") --------------------


def test_open_project_becomes_the_current_folder(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    (folder / "settings").mkdir(parents=True)
    (folder / "settings" / "settings.json").write_text(
        '{"meta": {"title": "Slayer Plus"}}', encoding="utf-8"
    )

    panel.open_project(folder)

    assert panel.current_folder == folder


def test_opening_a_second_project_replaces_the_first(panel: ExplorerPanel, tmp_path: Path) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()

    panel.open_project(first)
    panel.open_project(second)

    assert panel.current_folder == second
    assert Path(panel._settings_model.rootPath()) == second / "settings"


def test_opening_the_same_project_again_is_a_no_op(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)
    seen: list[Path | None] = []
    panel.active_project_changed.connect(seen.append)

    panel.open_project(folder)

    assert seen == []  # no redundant re-activate


def test_close_project_of_a_folder_that_is_not_open_is_a_no_op(panel: ExplorerPanel, tmp_path: Path) -> None:
    open_folder = tmp_path / "open"
    open_folder.mkdir()
    other_folder = tmp_path / "other"
    other_folder.mkdir()
    panel.open_project(open_folder)

    panel.close_project(other_folder)

    assert panel.current_folder == open_folder


def test_close_project_of_the_open_project_restores_the_placeholder(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "abcd1234"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_project(folder)

    assert panel.current_folder is None
    assert panel._no_project_label.isVisible() is True
    assert panel.settings_section.isVisible() is False


def test_close_active_project_closes_the_open_project(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    folder.mkdir()
    panel.open_project(folder)

    panel.close_active_project()

    assert panel.current_folder is None


def test_close_active_project_with_no_project_open_is_a_no_op(panel: ExplorerPanel) -> None:
    panel.close_active_project()  # should not raise

    assert panel.current_folder is None


def test_active_project_changed_fires_on_open_and_close(panel: ExplorerPanel, tmp_path: Path) -> None:
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    seen: list[Path | None] = []
    panel.active_project_changed.connect(seen.append)

    panel.open_project(first)
    panel.open_project(second)  # replaces "first", still fires
    panel.close_project(second)

    assert seen == [first, second, None]


def test_opening_a_second_project_closes_the_first(panel: ExplorerPanel, tmp_path: Path) -> None:
    # With only one project open at a time, replacing it *is* closing it -- MainWindow relies on
    # project_closed firing here to terminate the outgoing project's own RVT process.
    first = tmp_path / "first"
    first.mkdir()
    second = tmp_path / "second"
    second.mkdir()
    panel.open_project(first)
    seen: list[Path] = []
    panel.project_closed.connect(seen.append)

    panel.open_project(second)

    assert seen == [first]


def test_project_closed_fires_only_for_the_currently_open_project(panel: ExplorerPanel, tmp_path: Path) -> None:
    open_folder = tmp_path / "open"
    open_folder.mkdir()
    other_folder = tmp_path / "other"
    other_folder.mkdir()
    panel.open_project(open_folder)
    seen: list[Path] = []
    panel.project_closed.connect(seen.append)

    panel.close_project(other_folder)  # not open -- no-op, no signal
    panel.close_project(open_folder)

    assert seen == [open_folder]


# -- no-project spacer -----------------------------------------------------------------------


def test_no_project_spacer_is_visible_only_with_no_project_open(panel: ExplorerPanel, tmp_path: Path) -> None:
    assert panel._no_project_spacer.isVisible() is True

    folder = tmp_path / "abcd1234"
    folder.mkdir()
    panel.open_project(folder)
    assert panel._no_project_spacer.isVisible() is False

    panel.close_project(folder)
    assert panel._no_project_spacer.isVisible() is True


# -- Export/View Output.txt button row (PROMPT.md: "Underneath project tabs please add the
# following buttons: Export RVT File (on the left) and on the right: View Output.txt") -----------


def test_button_row_is_hidden_with_no_project_open(panel: ExplorerPanel) -> None:
    assert panel.button_row.isVisible() is False


def test_button_row_shows_once_a_project_opens_and_hides_once_it_closes(
    panel: ExplorerPanel, tmp_path: Path
) -> None:
    folder = tmp_path / "project"
    folder.mkdir()

    panel.open_project(folder)
    assert panel.button_row.isVisible() is True

    panel.close_project(folder)
    assert panel.button_row.isVisible() is False


def test_export_button_emits_export_requested(panel: ExplorerPanel, qtbot) -> None:
    seen = []
    panel.export_requested.connect(lambda: seen.append(True))

    qtbot.mouseClick(panel.export_button, Qt.MouseButton.LeftButton)

    assert seen == [True]


def test_view_output_button_emits_view_output_requested(panel: ExplorerPanel, qtbot) -> None:
    seen = []
    panel.view_output_requested.connect(lambda: seen.append(True))

    qtbot.mouseClick(panel.view_output_button, Qt.MouseButton.LeftButton)

    assert seen == [True]


def test_export_and_view_output_buttons_each_have_their_own_background_and_no_shared_style(
    panel: ExplorerPanel,
) -> None:
    # PROMPT.md: "please remove the bubble connecting the project dashboard buttons so they do
    # not appear connected, and give them a background colour to make it clear they are buttons".
    for button in (panel.export_button, panel.view_output_button):
        sheet = button.styleSheet()
        assert "background-color" in sheet
        assert button.autoRaise() is False
    # Each button's stylesheet is its own -- neither is empty/borrowed from a shared container
    # style that could read as one connected control.
    assert panel.export_button.styleSheet() == panel.view_output_button.styleSheet()


def test_view_output_button_is_labeled_view_compiled_megalo(panel: ExplorerPanel) -> None:
    assert panel.view_output_button.text() == "View Compiled Megalo"


def test_the_quick_launch_buttons_take_two_rows_so_none_is_squeezed(panel: ExplorerPanel) -> None:
    layout = panel.button_row.layout()

    def cell(button):
        row, column, _rows, columns = layout.getItemPosition(layout.indexOf(button))
        return row, column, columns

    assert cell(panel.export_button) == (0, 0, 1) and cell(panel.rvt_button) == (0, 1, 1)
    assert cell(panel.view_output_button) == (1, 0, 2)  # the whole second row
    assert not hasattr(panel, "view_decompiled_button")  # that one is the Scripts view's now


# -- Launch RVT button (PROMPT.md: "we are removing locations, and rvt ... please add a button in
# between Export File and View Compiled ... for Launch RVT") -----------------------------------


def test_rvt_button_starts_disabled(panel: ExplorerPanel) -> None:
    # PROMPT.md: "rvt should not be launchable if no project is open" -- true from construction,
    # before MainWindow ever gets a chance to enable it once a project opens.
    assert panel.rvt_button.isEnabled() is False


def test_rvt_button_sits_between_export_and_view_output(panel: ExplorerPanel) -> None:
    layout = panel.button_row.layout()
    widgets = [layout.itemAt(i).widget() for i in range(layout.count()) if layout.itemAt(i).widget() is not None]
    assert widgets.index(panel.export_button) < widgets.index(panel.rvt_button) < widgets.index(
        panel.view_output_button
    )


def test_rvt_button_emits_launch_rvt_requested(panel: ExplorerPanel, qtbot) -> None:
    # MainWindow owns actually enabling this button (see MainWindow._on_active_project_changed) --
    # enabled directly here to isolate what's under test: the click itself.
    panel.rvt_button.setEnabled(True)
    seen = []
    panel.launch_rvt_requested.connect(lambda: seen.append(True))

    qtbot.mouseClick(panel.rvt_button, Qt.MouseButton.LeftButton)

    assert seen == [True]
    assert panel.button_row.styleSheet() == ""


def test_dashboard_buttons_hover_with_the_theme_highlight_not_the_unthemed_light_role(
    panel: ExplorerPanel,
) -> None:
    # None of the dark/Whiley themes' own JSON sets a "light" QPalette role, so a hover styled
    # with `palette(light)` fell back to Qt's own unrelated (plain white) default -- unreadable
    # against those themes' own light button text. `palette(highlight)` is always themed.
    sheet = panel.export_button.styleSheet()
    assert "palette(light)" not in sheet
    assert "QToolButton:hover { background-color: palette(highlight)" in sheet


# -- Quick Launch section (PROMPT.md: "please then make a section 'Quick Launch' and add our
# buttons underneath") ---------------------------------------------------------------------------


def test_quick_launch_section_is_hidden_with_no_project_open(panel: ExplorerPanel) -> None:
    assert panel.quick_launch_section.isVisible() is False


def test_quick_launch_section_shows_once_a_project_opens(panel: ExplorerPanel, tmp_path: Path) -> None:
    folder = tmp_path / "project"
    folder.mkdir()

    panel.open_project(folder)
    assert panel.quick_launch_section.isVisible() is True

    panel.close_project(folder)
    assert panel.quick_launch_section.isVisible() is False


def test_stats_section_sits_above_quick_launch_and_settings(panel: ExplorerPanel) -> None:
    # PROMPT.md: "please move stats to the top of the panel".
    layout = panel.layout()
    widgets = [layout.itemAt(i).widget() for i in range(layout.count()) if layout.itemAt(i).widget() is not None]
    assert widgets.index(panel.stats_section) < widgets.index(panel.quick_launch_section)
    assert widgets.index(panel.quick_launch_section) < widgets.index(panel.settings_section)


@pytest.mark.parametrize(
    "button_name,key",
    [
        ("game_variants_button", "STANDARD_VARIANTS_LOC"),
        ("map_variants_button", "STANDARD_MAP_VARIANTS_LOC"),
        ("hopper_variants_button", "HOPPER_VARIANTS_LOC"),
        ("hopper_maps_button", "HOPPER_MAP_VARIANTS_LOC"),
        ("user_games_button", "PERSONAL_VARIANTS_LOC"),
        ("user_maps_button", "PERSONAL_MAPS_LOC"),
        ("hotreload_button", "HOTRELOAD_DIR_LOC"),
    ],
)
def test_builtin_folder_buttons_emit_open_builtin_folder_requested(
    panel: ExplorerPanel, qtbot, button_name: str, key: str
) -> None:
    seen = []
    panel.open_builtin_folder_requested.connect(seen.append)

    qtbot.mouseClick(getattr(panel, button_name), Qt.MouseButton.LeftButton)

    assert seen == [key]


def test_builtin_buttons_are_laid_out_two_per_row(panel: ExplorerPanel) -> None:
    # PROMPT.md: "col a / col b" -- Game Variants/Map Variants, Hopper Variants/Hopper Maps, User
    # Games/User Maps, each pair sharing a row. A fourth row holds "Open In-Reach Maps" alone,
    # spanning both columns (PROMPT.md: "a button for In-Reach maps ... quick launch built-in
    # buttons"), and a fifth "Open Hot Reload Folder", the same way.
    grid = panel.game_variants_button.parentWidget().layout()
    assert grid.rowCount() == 5
    assert grid.columnCount() == 2
    position = grid.getItemPosition(grid.indexOf(panel.inreach_maps_button))
    assert position == (3, 0, 1, 2)
    assert grid.getItemPosition(grid.indexOf(panel.hotreload_button)) == (4, 0, 1, 2)


# -- heading/subheading emphasis (PROMPT.md: "please update dashbaord so headings are bold and
# subheadings are italic") -----------------------------------------------------------------------


def test_section_headers_are_bold(panel: ExplorerPanel) -> None:
    for section in (panel.stats_section, panel.quick_launch_section, panel.settings_section):
        assert section._toggle.font().bold() is True


def test_locations_and_hot_reload_config_are_their_own_sections(panel: ExplorerPanel, tmp_path: Path) -> None:
    panel.open_project(tmp_path)
    layout = panel.layout()
    widgets = [layout.itemAt(i).widget() for i in range(layout.count()) if layout.itemAt(i).widget() is not None]

    assert panel.locations_section._toggle.text() == "Locations"
    assert panel.hot_reload_config_section._toggle.text() == "Hot Reload Config"
    assert panel.hotreload_button.text() == "Open Hot Reload Folder"
    assert panel.locations_section.body.isAncestorOf(panel.hotreload_button)
    assert panel.locations_section.body.isAncestorOf(panel.game_variants_button)
    assert not panel.quick_launch_section.body.isAncestorOf(panel.game_variants_button)
    assert [label.text() for label in panel.quick_launch_section.body.findChildren(QLabel)] == []
    order = [widgets.index(s) for s in (panel.quick_launch_section, panel.locations_section,
                                          panel.hot_reload_config_section, panel.notepad_section)]
    assert order == sorted(order)
    assert panel.locations_section.isVisible() and panel.hot_reload_config_section.isVisible()
    assert not panel.hot_reload_config_section.expanded


# -- RVT Settings, and the Stats bars ---------------------------------------------------------------------------


def test_the_settings_section_is_called_rvt_settings(panel: ExplorerPanel) -> None:
    assert panel.settings_section.title == "RVT Settings"


def _palette(highlight: str, base: str, text: str):
    from PyQt6.QtGui import QColor, QPalette

    palette = QPalette()
    palette.setColor(QPalette.ColorRole.Highlight, QColor(highlight))
    palette.setColor(QPalette.ColorRole.Base, QColor(base))
    palette.setColor(QPalette.ColorRole.Text, QColor(text))
    return palette


@pytest.mark.parametrize("highlight,base,text", [("#308cc6", "#ffffff", "#000000"), ("#2a82da", "#1e1e1e", "#ffffff")])
def test_the_stats_bars_fill_is_lighter_than_the_highlight_in_light_and_dark_themes(
    panel: ExplorerPanel, highlight: str, base: str, text: str
) -> None:
    from PyQt6.QtGui import QColor

    from in_reach_ide.explorer import progress_chunk_color

    palette = _palette(highlight, base, text)
    chunk = progress_chunk_color(palette)

    assert chunk != QColor(highlight)
    halfway = [(a + b) / 2 for a, b in zip(QColor(highlight).getRgb()[:3], QColor(base).getRgb()[:3])]
    assert all(abs(c - h) <= 1 for c, h in zip(chunk.getRgb()[:3], halfway))
    panel.refresh_progress_bars(palette)
    assert all(chunk.name() in bar.styleSheet() for bar in panel.progress_bars())


def test_the_stats_bars_text_is_smaller_than_the_panels(panel: ExplorerPanel) -> None:
    from in_reach_ide.explorer import PROGRESS_TEXT_SHRINK_PT

    panel.refresh_font_scale()

    for bar in panel.progress_bars():
        assert bar.font().pointSizeF() == pytest.approx(panel.font().pointSizeF() - PROGRESS_TEXT_SHRINK_PT)
    assert len(panel.progress_bars()) >= 10  # the space bar and every count's
